# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC select * from stock.gld_stock_trade order by trade_date desc

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.window import Window

# 假设 df 是你的数据源，已包含 symbol, price, timestamp, volume, conditions
# 1. 预处理：将毫秒级时间戳转换为分钟，并过滤出所有带有 ISO (条件 8) 的交易
df = spark.read.table("stock.finhub_silver")
iso_df = df.filter(F.array_contains(df.conditions, "8")) \
           .withColumn("trade_minute", F.from_unixtime(df.timestamp / 1000, "yyyy-MM-dd HH:mm"))

# 2. 窗口函数：计算每分钟的 VWAP 和成交量总和
# VWAP 的公式是: sum(price * volume) / sum(volume)
window_spec = Window.partitionBy("symbol", "trade_minute")

result_df = iso_df.withColumn("total_volume_per_min", F.sum("volume").over(window_spec)) \
                  .withColumn("weighted_price", F.col("price") * F.col("volume")) \
                  .withColumn("sum_weighted_price", F.sum("weighted_price").over(window_spec)) \
                  .withColumn("vwap", F.col("sum_weighted_price") / F.col("total_volume_per_min")) \
                  .select("symbol", "trade_minute", "total_volume_per_min", "vwap") \
                  .distinct() \
                  .orderBy("trade_minute")

# 3. 展示分析结果
result_df.show()

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.window import Window

# 1. 定义窗口：按时间排序，每 5 笔交易一组
# rowsBetween(-4, 0) 表示当前交易及其前 4 笔交易
window_5_trades = Window.partitionBy("symbol").orderBy("timestamp")

# 2. 计算 5 笔交易的滑动窗口统计
# 这里的 'vwap_5' 是机构在这 5 笔订单中的即时成本
# 'vol_5' 是这 5 笔的成交量之和，用来判断进攻力度
analysis_df = df.withColumn("vwap_5", 
    F.sum(F.col("price") * F.col("volume")).over(window_5_trades.rowsBetween(-4, 0)) / 
    F.sum("volume").over(window_5_trades.rowsBetween(-4, 0))
) \
.withColumn("vol_5", F.sum("volume").over(window_5_trades.rowsBetween(-4, 0)))

# 3. 筛选：只提取出“机构暴力吸筹”的时刻
# 条件：5 笔内的总成交量大于 500 且 价格持续上涨
final_signals = analysis_df.filter((F.col("vol_5") > 500)) \
                           .select("symbol", "timestamp", "price", "vwap_5", "vol_5") \
                           .orderBy("timestamp")

final_signals.show()

# COMMAND ----------

# 计算成交量动能：如果当前 vol_5 是前一个窗口的 2 倍以上，标记为“扫盘信号”
signal_df = analysis_df.withColumn("prev_vol_5", F.lag("vol_5").over(window_5_trades)) \
                       .withColumn("volume_surge", F.col("vol_5") / F.col("prev_vol_5")) \
                       .withColumn("is_sweep", F.when(F.col("volume_surge") > 2.0, "SIGNAL: SWEEP").otherwise("Normal"))

signal_df.filter(F.col("is_sweep") == "SIGNAL: SWEEP").show()

# COMMAND ----------

import matplotlib.pyplot as plt
import pandas as pd

# 将 Spark DataFrame 转为 Pandas
plot_df = df_final.toPandas()

# 转换时间戳为可读格式（如需要）
plot_df['timestamp'] = pd.to_datetime(plot_df['timestamp'], unit='ms')

plt.figure(figsize=(15, 6))

# 绘制价格曲线
plt.plot(plot_df['timestamp'], plot_df['price'], color='gray', alpha=0.3, label='Price')

# 标记 Bullish 信号 (红色上箭头)
bullish = plot_df[plot_df['intent'] == 'Bullish_Sweep']
plt.scatter(bullish['timestamp'], bullish['price'], color='red', marker='^', s=50, label='Bullish Sweep')

# 标记 Bearish 信号 (绿色下箭头)
bearish = plot_df[plot_df['intent'] == 'Bearish_Sweep']
plt.scatter(bearish['timestamp'], bearish['price'], color='green', marker='v', s=50, label='Bearish Sweep')

plt.title('AAPL: Institutional Sweep Intent Analysis')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# COMMAND ----------

from pyspark.sql import functions as F

# 1. 创建价格区间 (Bucketizing)
# 将价格向下取整到 10 的倍数，例如 261 -> 260
bucket_df = df_final.withColumn("price_bucket", (F.floor(F.col("price") / 10) * 10))

# 2. 统计各区间的机构强度
institution_strength = bucket_df.filter(F.col("is_sweep") == "SIGNAL: SWEEP") \
    .groupBy("price_bucket") \
    .agg(
        F.sum("vol_5").alias("total_institutional_volume"),
        F.count("*").alias("sweep_frequency")
    ) \
    .orderBy(F.desc("total_institutional_volume"))

institution_strength.show()
